Win stage0
Gepardec/weckdengeparden pull request #83
Opened 2020-11-12 17:32 UTC by agnesHi

Erster Versuch; Enum Klassen, Pom, Readme, ChallengesResource

2020-11-13 13:38 UTC, matfa42 requested changes

2020-11-13 13:38 UTC, matfa42 commented on src/test/java/com/gepardec/wdg/application/validation/Base64ValidatorTest.java
> +    // Test will fail because of a broken CodePart
Vllt sollte man bei kommentaren immer einen prefix ala WIN-Stage? einfuegen.

2020-11-13 13:38 UTC, matfa42 commented on src/main/java/com/gepardec/wdg/challenge/ChallengesResource.java
> +            correctAnswer = challenge.getAnswer().trim().contains(answer.getAnswer().trim());
Mittles contains wird das nicht ganz funktionieren, schöner wäre es, eine überprüfung einzubauen ob wirklich ein Link zu einem Pull Request geschickt wird (sprich pattern matching mit regex).

Tipp: Wir wissen das der string IMMER so am anfang aussehen soll 'https://github.com/Gepardec/weckdengeparden/pull/' und danach MUSS eine Zahl kommen. Somit koennte man den string bis zum letzten "/" abschneiden und pruefen, und alles danach auf eine Zahl testen.
Aufpassen: der link kann z.B. so aussehen: 
https://github.com/Gepardec/weckdengeparden/pull/   83
https://github.com/Gepardec/weckdengeparden/pull/   83/

2020-11-18 16:15 UTC, agnesHi commented
pom  --> dependency gelöscht
AnswerValidatorTest --> Namen verändert (Falscher Test, Richtiger Code)
URLValidatorTest --> Tests sollen geschrieben werden  (URL Validator <- neue Klasse zum Überprüfen des Links zum Pullrequest)
Base64ValidatorTest --> RegEx manipuliert (Richtiger Test, Falscher Code)

2020-11-20 11:41 UTC, philzelinger commented
Pull request wird abgelehnt, da besprochen wurde, das pro stage ein eigener branch erstellt wird und für diese einzelnen branches dann ein pull request erstellt wird, nicht so wie hier alles in einem pull request

2020-11-20 11:41 UTC, closed without merging