Challenge2-Tests
Gepardec/weckdengeparden pull request #97
Opened 2020-12-23 00:31 UTC by nebojsa959

Die Tests für Challenge 2 + allgemeine Anpassungen in der Testklasse.

2020-12-28 15:23 UTC, matfa42 requested changes

2020-12-28 15:23 UTC, matfa42 commented on src/main/java/com/gepardec/wdg/application/filter/RequestInputFilter.java
> +    private static final Pattern URL_PATH_REGEX_PATTER = Pattern.compile("(/challenge/)\\d+(/url)");
Bitte hier nicht einen zweiten regex pattern erstellen sondern den ersten umbennen und um den url pattern erweitern

2020-12-28 15:23 UTC, matfa42 commented on src/test/java/com/gepardec/wdg/challenge/ChallengeResourceTest.java
> +import org.junit.jupiter.api.Disabled;
delete unused import bitte.

2020-12-28 15:23 UTC, matfa42 commented on src/test/java/com/gepardec/wdg/challenge/ChallengeResourceTest.java
> +        answer.setUrl("Ivalid url");
bitte typo fixen

2021-01-08 08:55 UTC, philzelinger reviewed
Passt alles, Approve folgt zu einem späteren Zeitpunkt

2021-01-15 08:40 UTC, philzelinger approved these changes
Fixes in Ordnung

2021-01-15 08:42 UTC, matfa42 approved these changes

2021-01-15 08:42 UTC, merged